version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ahmed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ah39aziz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ahmed
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
