version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ahmed
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://ahmed:ahmed@db:5432/mydatabase



