version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ahmed
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
    - "80:80"
  app:
    build: .
    
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://ahmed:ahmed@db:5432/mydatabase
      PGADMIN_DEFAULT_EMAIL: ah39aziz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ahmed
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:




